---
title: "Dependency licenses"
---

This package uses code from the following packages, which are distributed under the licenses listed below.

<h1> Rcpp </h1>

by: Dirk Eddelbuettel, Romain Francois, JJ Allaire, Kevin Ushey, Qiang Kou, Nathan Russell, Iñaki Ucar, Doug Bates, and John Chambers

https://cran.r-project.org/web/packages/Rcpp/index.html  
https://github.com/RcppCore/Rcpp/tree/master

GNU General Public License v2.0  
https://github.com/RcppCore/Rcpp/blob/master/LICENSE  
https://github.com/RcppCore/Rcpp/blob/0905d92e0046de5f171d4fde752d97e8733738be/LICENSE

<h1> Boost / BH </h1>

Copyright Beman Dawes, David Abrahams, 1998-2005.  
Copyright Rene Rivera 2004-2007.

https://www.boost.org/  
https://github.com/boostorg

Boost license 1.0  
https://www.boost.org/LICENSE_1_0.txt  
https://github.com/boostorg/boost/blob/master/LICENSE_1_0.txt

"Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE."

<h1> Eigen </h1>

The Eigen project was started by Benoît Jacob (founder) and Gaël Guennebaud (guru). Many other people have since contributed their talents to help make Eigen successful.

https://eigen.tuxfamily.org/  
https://gitlab.com/libeigen/eigen

MPL2 (Mozilla Public License)  
https://www.mozilla.org/en-US/MPL/2.0/FAQ/

<h1> nlopt </h1>

Steven G. Johnson  
The NLopt nonlinear-optimization package 

http://github.com/stevengj/nlopt  
https://nlopt.readthedocs.io/en/latest/

GNU Lesser General Public License (LGPL)  
https://nlopt.readthedocs.io/en/latest/NLopt_License_and_Copyright/

<h1> pcg </h1>

Melissa E. O'Neill  
https://www.cs.hmc.edu/~oneill/index.html

https://www.pcg-random.org/  
https://github.com/imneme/pcg-cpp

Apache 2.0 and The MIT License

<h1> ggplot2 </h1>

by: ggplot2 core developer team

https://ggplot2.tidyverse.org/

The MIT license  
https://github.com/tidyverse/ggplot2

<h1> MASS </h1> 

... must fill in.
