# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_known_celltypes <- function() {
    invisible(.Call(`_neurons_init_known_celltypes`))
}

set_cell_type_params <- function(type_name, valence, temporal_modulation_bias, temporal_modulation_timeconstant, temporal_modulation_amplitude, transmission_velocity, v_ceiling, I_ceiling, I_spike, coupling_scaling_factor, spike_potential, resting_potential, threshold) {
    invisible(.Call(`_neurons_set_cell_type_params`, type_name, valence, temporal_modulation_bias, temporal_modulation_timeconstant, temporal_modulation_amplitude, transmission_velocity, v_ceiling, I_ceiling, I_spike, coupling_scaling_factor, spike_potential, resting_potential, threshold))
}

